### ISSUE TITLE
I wrote a Gradio interface and fixed the build instructions

### ISSUE THREAD

**Issue by RamboRogers** [hotshotco/Hotshot-XL#26]
If you want to take the app.py file it will give you a gradio interface.
![interface](https://github.com/hotshotco/Hotshot-XL/assets/7763805/a25f1d37-d79e-46c8-9635-14429a009ce8)

[https://github.com/RamboRogers/Hotshot-XL-Gradio](https://github.com/RamboRogers/Hotshot-XL-Gradio)

**Comment by RamboRogers** [comment]
[https://github.com/RamboRogers/Hotshot-XL-Gradio](https://github.com/RamboRogers/Hotshot-XL-Gradio)

**Comment by GARV-k** [comment]
It doesn't work for me. I did it with the same settings as your example. Just for a different prompt but the output was just a black image.
Also I got a warning : 
seed: 3461188826
Loading pipeline components...: 100%|███████████████████████████████████████████| 7/7 [05:28<00:00, 46.93s/it]
Warning - setting num_images_per_prompt = 1 because video_length = 8
100%|██████████████████████████████████████████████████████████████████████| 30/30 [1:50:08<00:00, 220.28s/it]
100%|███████████████████████████████████████████████████████████████████████████| 8/8 [03:25<00:00, 25.72s/it]
seed: 2958070946

**Comment by RamboRogers** [comment]
I need to rework this repo and pin versions. It's so out of date now I don't think it matters.
